apiVersion: apps/v1
kind: Deployment

metadata:
  name: student-hub

spec:
  replicas: 2

  selector:
    matchLabels:
      app: student-hub

  template:
    metadata:
      labels:
        app: student-hub

    spec:
      containers:
        - name: student-hub
          image: nginx:latest

          ports:
            - containerPort: 80
